# Generated by Django 5.2.1 on 2025-06-10 18:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Streams',
            fields=[
                ('streamid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('stream_url', models.URLField()),
                ('stream_name', models.CharField(max_length=20)),
                ('stream_description', models.CharField(max_length=250)),
                ('face_detection_flag', models.BooleanField(default=False)),
                ('confidence_threshold', models.FloatField(max_length=1)),
            ],
        ),
    ]
