# Generated by Django 5.2.1 on 2025-06-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtsp_stream', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streams',
            name='confidence_threshold',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='streams',
            name='stream_description',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='streams',
            name='stream_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
