# Generated by Django 5.2.1 on 2025-06-11 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtsp_stream', '0002_alter_streams_confidence_threshold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streams',
            name='confidence_threshold',
        ),
        migrations.RemoveField(
            model_name='streams',
            name='face_detection_flag',
        ),
        migrations.RemoveField(
            model_name='streams',
            name='stream_description',
        ),
        migrations.RemoveField(
            model_name='streams',
            name='stream_name',
        ),
    ]
