# Generated by Django 5.2.1 on 2025-06-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtsp_stream', '0003_remove_streams_confidence_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='streams',
            name='face_detection_flag',
            field=models.BooleanField(default=False),
        ),
    ]
