# Generated by Django 5.2.1 on 2025-06-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtsp_stream', '0004_streams_face_detection_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='streams',
            name='stream_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
