# Generated by Django 5.2.1 on 2025-06-11 19:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtsp_stream', '0005_streams_stream_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('detection_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('detect_timestamp', models.DateTimeField()),
                ('stream_ref', models.URLField()),
                ('confidence_score', models.FloatField()),
            ],
        ),
    ]
