# Generated by Django 5.2.1 on 2025-06-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtsp_stream', '0006_detection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detection',
            name='detect_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detection',
            name='stream_ref',
            field=models.URLField(blank=True, null=True),
        ),
    ]
